spring:
  datasource:
        driver-class-name: org.postgresql.Driver
        password: 'root'
        url: 'jdbc:postgresql://localhost:5432/laxmini'
        username: 'postgres'
#
#
#
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver